export interface QueryResponse {
  boroughs: Record<string, number>
  summary: string
}

const DUMMY_RESPONSE: QueryResponse = {
  boroughs: {
    // ── London ────────────────────────────────────────────────────────────────
    'Barnet': 82,
    'Camden': 45,
    'Hackney': 63,
    'Islington': 38,
    'Tower Hamlets': 71,
    'Southwark': 56,
    'Lambeth': 49,
    'Westminster': 22,
    'Kensington and Chelsea': 15,
    'Hammersmith and Fulham': 34,
    'Wandsworth': 67,
    'Lewisham': 74,
    'Greenwich': 78,
    'Bexley': 85,
    'Bromley': 88,
    'Croydon': 79,
    'Merton': 61,
    'Kingston upon Thames': 72,
    'Richmond upon Thames': 41,
    'Hounslow': 58,
    'Ealing': 65,
    'Hillingdon': 76,
    'Harrow': 69,
    'Brent': 53,
    'Haringey': 47,
    'Enfield': 81,
    'Waltham Forest': 70,
    'Redbridge': 73,
    'Havering': 84,
    'Barking and Dagenham': 77,
    'Newham': 66,
    'City of London': 18,
    'Sutton': 68,
    // ── South East ────────────────────────────────────────────────────────────
    'Brighton and Hove': 44,
    'Isle of Wight': 75,
    'Medway': 71,
    'Milton Keynes': 78,
    'Oxford': 33,
    'Portsmouth': 62,
    'Reading': 60,
    'Slough': 68,
    'Southampton': 54,
    'Bracknell Forest': 72,
    'West Berkshire': 74,
    'Windsor and Maidenhead': 55,
    'Wokingham': 67,
    'Aylesbury Vale': 75,
    'Chiltern': 63,
    'South Bucks': 64,
    'Wycombe': 70,
    'Eastbourne': 58,
    'Hastings': 49,
    'Lewes': 61,
    'Rother': 66,
    'Wealden': 71,
    'Adur': 65,
    'Arun': 70,
    'Chichester': 67,
    'Crawley': 72,
    'Horsham': 74,
    'Mid Sussex': 72,
    'Worthing': 66,
    'Ashford': 68,
    'Canterbury': 57,
    'Dartford': 71,
    'Dover': 69,
    'Gravesham': 67,
    'Maidstone': 74,
    'Sevenoaks': 70,
    'Shepway': 64,
    'Swale': 70,
    'Thanet': 58,
    'Tonbridge and Malling': 73,
    'Tunbridge Wells': 66,
    'Elmbridge': 52,
    'Epsom and Ewell': 55,
    'Guildford': 49,
    'Mole Valley': 69,
    'Reigate and Banstead': 65,
    'Runnymede': 61,
    'Spelthorne': 63,
    'Surrey Heath': 72,
    'Tandridge': 65,
    'Waverley': 68,
    'Woking': 60,
    'Basingstoke and Deane': 80,
    'East Hampshire': 73,
    'Eastleigh': 66,
    'Fareham': 71,
    'Gosport': 64,
    'Hart': 76,
    'Havant': 63,
    'New Forest': 77,
    'Rushmoor': 68,
    'Test Valley': 75,
    'Winchester': 69,
    'Cherwell': 74,
    'South Oxfordshire': 71,
    'Vale of White Horse': 72,
    'West Oxfordshire': 76,
    // ── South West ────────────────────────────────────────────────────────────
    'Bath and North East Somerset': 43,
    'Bristol, City of': 52,
    'Cornwall': 83,
    'North Somerset': 68,
    'Plymouth': 71,
    'South Gloucestershire': 72,
    'Swindon': 75,
    'Torbay': 76,
    'Wiltshire': 77,
    'Bournemouth': 58,
    'Christchurch': 71,
    'Poole': 61,
    'East Dorset': 73,
    'North Dorset': 75,
    'Purbeck': 73,
    'West Dorset': 74,
    'Weymouth and Portland': 63,
    'East Devon': 70,
    'Exeter': 61,
    'Mid Devon': 74,
    'North Devon': 71,
    'South Hams': 77,
    'Teignbridge': 68,
    'Torridge': 76,
    'West Devon': 79,
    'Cheltenham': 55,
    'Cotswold': 76,
    'Forest of Dean': 68,
    'Gloucester': 69,
    'Stroud': 66,
    'Tewkesbury': 74,
    'Mendip': 72,
    'Sedgemoor': 69,
    'South Somerset': 71,
    'Taunton Deane': 68,
    'West Somerset': 78,
    'Isles of Scilly': 85,
    // ── East of England ───────────────────────────────────────────────────────
    'Luton': 58,
    'Peterborough': 74,
    'Southend-on-Sea': 60,
    'Thurrock': 67,
    'Bedford': 73,
    'Central Bedfordshire': 75,
    'Cambridge': 39,
    'East Cambridgeshire': 74,
    'Fenland': 70,
    'Huntingdonshire': 76,
    'South Cambridgeshire': 77,
    'Basildon': 64,
    'Braintree': 71,
    'Brentwood': 67,
    'Castle Point': 66,
    'Chelmsford': 82,
    'Colchester': 77,
    'Epping Forest': 65,
    'Harlow': 61,
    'Maldon': 72,
    'Rochford': 69,
    'Tendring': 68,
    'Uttlesford': 76,
    'Broxbourne': 68,
    'Dacorum': 66,
    'East Hertfordshire': 72,
    'Hertsmere': 63,
    'North Hertfordshire': 70,
    'St Albans': 54,
    'Stevenage': 68,
    'Three Rivers': 61,
    'Watford': 53,
    'Welwyn Hatfield': 65,
    'Broadland': 73,
    'Breckland': 74,
    'Great Yarmouth': 67,
    "King's Lynn and West Norfolk": 74,
    'North Norfolk': 76,
    'Norwich': 65,
    'South Norfolk': 75,
    'Babergh': 72,
    'Forest Heath': 73,
    'Ipswich': 70,
    'Mid Suffolk': 74,
    'St Edmundsbury': 75,
    'Suffolk Coastal': 74,
    'Waveney': 69,
    // ── East Midlands ─────────────────────────────────────────────────────────
    'Derby': 46,
    'Leicester': 48,
    'Nottingham': 64,
    'Rutland': 79,
    'Amber Valley': 69,
    'Bolsover': 62,
    'Chesterfield': 66,
    'Derbyshire Dales': 78,
    'Erewash': 66,
    'High Peak': 71,
    'North East Derbyshire': 67,
    'South Derbyshire': 72,
    'Blaby': 73,
    'Charnwood': 70,
    'Harborough': 75,
    'Hinckley and Bosworth': 72,
    'Melton': 74,
    'North West Leicestershire': 70,
    'Oadby and Wigston': 65,
    'Boston': 74,
    'East Lindsey': 72,
    'Lincoln': 79,
    'North Kesteven': 75,
    'South Holland': 76,
    'South Kesteven': 74,
    'West Lindsey': 71,
    'Corby': 65,
    'Daventry': 76,
    'East Northamptonshire': 74,
    'Kettering': 68,
    'Northampton': 71,
    'South Northamptonshire': 77,
    'Wellingborough': 67,
    'Ashfield': 64,
    'Bassetlaw': 68,
    'Broxtowe': 67,
    'Gedling': 69,
    'Mansfield': 74,
    'Newark and Sherwood': 71,
    'Rushcliffe': 74,
    // ── West Midlands ─────────────────────────────────────────────────────────
    'Birmingham': 55,
    'Coventry': 51,
    'Dudley': 57,
    'Sandwell': 48,
    'Solihull': 76,
    'Walsall': 62,
    'Wolverhampton': 39,
    'Herefordshire, County of': 78,
    'Shropshire': 75,
    'Stoke-on-Trent': 83,
    'Telford and Wrekin': 68,
    'Cannock Chase': 65,
    'East Staffordshire': 67,
    'Lichfield': 72,
    'Newcastle-under-Lyme': 61,
    'South Staffordshire': 72,
    'Stafford': 69,
    'Staffordshire Moorlands': 71,
    'Tamworth': 67,
    'North Warwickshire': 73,
    'Nuneaton and Bedworth': 63,
    'Rugby': 70,
    'Stratford-on-Avon': 74,
    'Warwick': 68,
    'Bromsgrove': 70,
    'Malvern Hills': 74,
    'Redditch': 66,
    'Worcester': 71,
    'Wychavon': 73,
    'Wyre Forest': 67,
    // ── Yorkshire & Humber ────────────────────────────────────────────────────
    'Barnsley': 67,
    'Bradford': 73,
    'Calderdale': 58,
    'Doncaster': 70,
    'Kirklees': 71,
    'Leeds': 68,
    'Rotherham': 63,
    'Sheffield': 59,
    'Wakefield': 74,
    'East Riding of Yorkshire': 73,
    'Kingston upon Hull, City of': 65,
    'York': 52,
    'Craven': 74,
    'Hambleton': 76,
    'Harrogate': 67,
    'Richmondshire': 79,
    'Ryedale': 77,
    'Scarborough': 66,
    'Selby': 74,
    'North East Lincolnshire': 63,
    'North Lincolnshire': 68,
    // ── North West ────────────────────────────────────────────────────────────
    'Bolton': 74,
    'Bury': 67,
    'Manchester': 62,
    'Oldham': 57,
    'Rochdale': 61,
    'Salford': 69,
    'Stockport': 65,
    'Tameside': 61,
    'Trafford': 65,
    'Wigan': 78,
    'Knowsley': 60,
    'Liverpool': 43,
    'Sefton': 66,
    'St. Helens': 64,
    'Wirral': 59,
    'Blackburn with Darwen': 63,
    'Blackpool': 72,
    'Cheshire East': 72,
    'Cheshire West and Chester': 68,
    'Halton': 64,
    'Warrington': 70,
    'Burnley': 68,
    'Chorley': 71,
    'Fylde': 73,
    'Hyndburn': 62,
    'Lancaster': 69,
    'Pendle': 65,
    'Preston': 76,
    'Ribble Valley': 76,
    'Rossendale': 63,
    'South Ribble': 70,
    'West Lancashire': 72,
    'Wyre': 71,
    'Allerdale': 72,
    'Barrow-in-Furness': 66,
    'Carlisle': 73,
    'Copeland': 70,
    'Eden': 78,
    'South Lakeland': 74,
    // ── North East ────────────────────────────────────────────────────────────
    'Gateshead': 71,
    'Newcastle upon Tyne': 57,
    'North Tyneside': 82,
    'South Tyneside': 75,
    'Sunderland': 80,
    'County Durham': 79,
    'Darlington': 72,
    'Hartlepool': 73,
    'Middlesbrough': 64,
    'Northumberland': 77,
    'Redcar and Cleveland': 68,
    'Stockton-on-Tees': 68,
  },
  summary: 'Based on your property development proposal, we analysed planning permission approval rates across English councils. Warmer colours indicate higher approval likelihood.',
}

export async function submitQuery(_message: string): Promise<QueryResponse> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 800))
  return DUMMY_RESPONSE
}
